CREATE DATABASE `COMGAS` /*!40100 DEFAULT CHARACTER SET latin1 */;

DROP TABLE IF EXISTS `DUTOS`;

CREATE TABLE `DUTOS` (
  `ID_TUBO` int DEFAULT NULL,
  `DATA_INSTALACAO` datetime DEFAULT NULL,
  `PRESSAO` int DEFAULT NULL,
  `UNIDADE_PRESSAO` text,
  `LATITUDE` DECIMAL(20,10),
  `LONGITUDE` DECIMAL(20,10),
  `NOME_LOGRADOURO` text,
  `QTDE_CLIENTES` int DEFAULT NULL,
  `DIAMETRO` int DEFAULT NULL,
  `UNIDADE_DIAMETRO` text,
  `MATERIAL` text
) ;
